#!/usr/bin/env bash

# NOTE: this file will be automatically installed to a system-wide location if aws-runas
# was installed via .deb or .rpm packages
#
# Copy this file to /etc/bash_completion.d/aws-runas to enable automatic completion
# for aws-runas.  Otherwise, you can install this file at some accessible location,
# then in a user's .bash_profile, add the following lines:
#
#  PROG=aws-runas
#  source path/to/aws-runas-bash-completion

: ${PROG:=$(basename ${BASH_SOURCE})}

_cli_bash_autocomplete() {
  if [[ "${COMP_WORDS[0]}" != "source" ]]; then
    local cur opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    if [[ "$cur" == "-"* ]]; then
      opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} ${cur} --generate-bash-completion )
    else
      opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )
    fi
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
  fi
}

complete -o bashdefault -o default -o nospace -F _cli_bash_autocomplete $PROG
unset PROG